server:
  port: 8081

spring:
  application:
    name: history-service

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: password
    listener:
      simple:
        default-requeue-rejected: false

  datasource:
    url: jdbc:postgresql://postgres:5432/medsync
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://medsync-auth:8079/oauth2/jwks

app:
  rabbitmq:
    queue: history-queue

graphql:
  servlet:
    enabled: true
    mapping: /graphql

logging:
  level:
    br:
      com:
        fiap:
          postech:
            medsync:
              notification: DEBUG
